/*
 * repostate.h -- the list of package-repo manifest URLs pikostore points
 * at (Packages tab -> Settings).
 *
 * Split out like romstate.h, and for the same reason: pure libc/libstdc++,
 * no FLTK, no X, no /etc/zaurus needed to exercise it. See
 * tests/repostate-test.cxx.
 *
 * Unlike manifest/update-history (romstate.h), this file is not generated
 * by anything in the piko repo -- it is pikostore's own state, written by
 * this app alone the first time the user adds or removes a repo.
 */

#ifndef PIKOSTORE_REPOSTATE_H
#define PIKOSTORE_REPOSTATE_H

#include <stdio.h>

#include <string>
#include <vector>

#include "romstate.h"

namespace repostate {

/* This repo's own manifest, generated by tools/generate-basic-repo.sh.
 * Used whenever REPOS_PATH does not exist yet, so a fresh install has
 * exactly one package source without needing a settings file at all. */
const char *const DEFAULT_REPO =
    "https://raw.githubusercontent.com/sugarkrap/pikostore/main/packages/manifest.yaml";

/* One repo URL per line. '#' comments and blank lines are ignored -- same
 * convention as every other flat text file in this app. A line is used
 * verbatim (trimmed), not parsed further: this file stores manifest URLs,
 * nothing else.
 *
 * A missing file is not an error: it means the user has never touched
 * Settings, and the result is exactly one entry, DEFAULT_REPO -- the same
 * thing writing that single line to REPOS_PATH would have produced. */
inline std::vector<std::string> read_repos(const char *path)
{
    std::vector<std::string> repos;
    FILE *f = fopen(path, "r");
    char line[1024];

    if (!f) {
        repos.push_back(DEFAULT_REPO);
        return repos;
    }

    while (fgets(line, sizeof(line), f)) {
        std::string s = romstate::trim(std::string(line));
        if (s.empty() || s[0] == '#')
            continue;
        repos.push_back(s);
    }
    fclose(f);
    return repos;
}

/* Plain overwrite, same as every other bit of state this app writes.
 * Returns false only if the file could not even be opened. */
inline bool write_repos(const char *path, const std::vector<std::string> &repos)
{
    FILE *f = fopen(path, "w");
    if (!f)
        return false;

    for (std::vector<std::string>::const_iterator it = repos.begin();
         it != repos.end(); ++it)
        fprintf(f, "%s\n", it->c_str());

    fclose(f);
    return true;
}

/* Appends url to repos unless it is empty (after trimming) or already
 * present (exact match). Returns true iff the list changed. Pure
 * in-memory list manipulation -- callers persist with write_repos()
 * themselves -- so this is unit-testable with no filesystem I/O. */
inline bool add_repo(std::vector<std::string> &repos, const std::string &url)
{
    std::string s = romstate::trim(url);
    if (s.empty())
        return false;

    for (std::vector<std::string>::const_iterator it = repos.begin();
         it != repos.end(); ++it) {
        if (*it == s)
            return false;
    }
    repos.push_back(s);
    return true;
}

} /* namespace repostate */

#endif /* PIKOSTORE_REPOSTATE_H */
