#!/bin/sh
set -eu

# tools/generate-basic-repo.sh -- builds each packages/<name> submodule's
# .ipk (where that is currently possible) and (re)generates
# packages/manifest.yaml: the file pikostore itself reads, by default via
# this repo's raw GitHub URL, to know what packages exist and where their
# .ipk lives.
#
# Run this BY HAND, from a checkout that has a sibling ../piko with its
# cross-toolchain built (tools/build-uclibc-toolchain.sh in that repo), and
# whatever additional stage each package itself needs (zmenunx wants the
# SDL runtime staged too -- see its own build-package.sh). This is not run
# by CI: the toolchain build alone is a multi-hour, multi-GB job, the same
# one piko's own build-piko-zip.yml pays for. After a successful run,
# commit the new/changed packages/*.ipk (tracked via git-lfs, see
# .gitattributes) together with the regenerated manifest.yaml.
#
# A package whose build fails, or whose prerequisites are missing, is
# listed in the manifest WITHOUT an ipk: field rather than aborting the
# whole run -- one broken package must not hide the others.
#
# Usage:
#   tools/generate-basic-repo.sh [--out DIR] [--raw-base URL]
#
#   --out DIR       where to write manifest.yaml and the built .ipk files
#                    (default: packages/, i.e. this repo's own packages dir)
#   --raw-base URL  base URL the manifest's ipk: fields are built from,
#                    "<raw-base>/<filename>" (default: this repo's raw
#                    GitHub content URL for packages/ on main)

REPO="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
PKGDIR="$REPO/packages"
OUTDIR="$PKGDIR"
RAW_BASE="https://raw.githubusercontent.com/sugarkrap/pikostore/main/packages"

while [ $# -gt 0 ]; do
    case "$1" in
        --out)      OUTDIR="${2:?--out needs a value}"; shift 2 ;;
        --raw-base) RAW_BASE="${2:?--raw-base needs a value}"; shift 2 ;;
        -h|--help)  sed -n '3,26p' "$0"; exit 0 ;;
        *) echo "FAILED: unknown option: $1" >&2; exit 1 ;;
    esac
done

mkdir -p "$OUTDIR"
OUTDIR="$(CDPATH= cd -- "$OUTDIR" && pwd)"

# A sibling ../piko checkout is where make-ipk.sh, the cross-toolchain and
# every staged runtime (X11, SDL, ...) live. Its absence is not fatal here
# -- it just means every package below gets listed without an ipk: URL.
PIKO="$(CDPATH= cd -- "$REPO/../piko" 2>/dev/null && pwd)" || PIKO=""
MAKEIPK=""
if [ -n "$PIKO" ] && [ -x "$PIKO/tools/make-ipk.sh" ]; then
    MAKEIPK="$PIKO/tools/make-ipk.sh"
fi
TOOLCHAIN_GCC="$PIKO/toolchain/x-tools/arm-unknown-linux-uclibcgnueabi/bin/arm-unknown-linux-uclibcgnueabi-gcc"

if [ -z "$MAKEIPK" ]; then
    echo "==> WARNING: no sibling ../piko checkout with tools/make-ipk.sh found." >&2
    echo "    Every package below will be listed without an ipk: URL. Build" >&2
    echo "    ../piko (its cross-toolchain, plus whatever stage each package" >&2
    echo "    needs) and re-run this script to actually produce .ipk files." >&2
else
    # zmenunx's and otcraft's own build scripts (and otQuake's Makefile)
    # each resolve their OWN "../piko" sibling relative to their own
    # directory -- i.e. packages/<name>/../piko, which is packages/piko --
    # not relative to this repo's root, and that lookup has no env-var
    # override. A symlink here is what makes all three find the same
    # checkout this script already found.
    if [ -L "$PKGDIR/piko" ] || [ ! -e "$PKGDIR/piko" ]; then
        ln -sfn "$PIKO" "$PKGDIR/piko"
    else
        echo "==> WARNING: $PKGDIR/piko exists and is not a symlink -- leaving it" >&2
        echo "    alone, but packages/*/build-package.sh look for ../piko there" >&2
        echo "    and may not find $PIKO." >&2
    fi
fi

MANIFEST="$OUTDIR/manifest.yaml"
TMP_MANIFEST="$(mktemp)"
trap 'rm -f "$TMP_MANIFEST"' EXIT INT TERM

{
    echo "# packages/manifest.yaml -- generated by tools/generate-basic-repo.sh"
    echo "# Do not hand-edit; re-run the generator instead."
    echo "version: 1"
    echo "packages:"
} > "$TMP_MANIFEST"

pkg_version() {
    # $1 = submodule dir. Same fallback build-package.sh in zmenunx/otcraft
    # already use: git describe, or a fixed placeholder with no git.
    ( cd "$1" && git describe --always --dirty 2>/dev/null ) || echo "0.0.0-unknown"
}

# emit_entry NAME REPO_URL DESC [IPK_FILENAME]
emit_entry() {
    name="$1"; repo="$2"; desc="$3"; ipk="${4:-}"
    {
        printf '  - name: "%s"\n' "$name"
        printf '    repo: "%s"\n' "$repo"
        printf '    description: "%s"\n' "$desc"
        if [ -n "$ipk" ]; then
            printf '    ipk: "%s/%s"\n' "$RAW_BASE" "$ipk"
        fi
    } >> "$TMP_MANIFEST"
}

# newest_ipk PATTERN DIR -- the most recently modified file in DIR matching
# PATTERN, or nothing. Called right after a build so this run's output is
# never confused with a stale .ipk left over from an earlier run.
newest_ipk() {
    ( cd "$2" 2>/dev/null && ls -t $1 2>/dev/null | head -1 ) || true
}

# ---------------------------------------------------------------------
# zmenunx -- has its own build-package.sh (needs ../piko's toolchain AND
# its staged SDL runtime -- see that script's own header).
#
# KNOWN ISSUE, not fixed here (no push access to either repo from this
# tool): as of this writing, zmenunx/build-package.sh passes --postinst to
# make-ipk.sh, which make-ipk.sh does not implement. That build WILL fail
# until one side or the other is updated upstream. The failure is caught
# below, same as any other build failure -- it just means gmenunx has no
# ipk: URL until that gets fixed.
# ---------------------------------------------------------------------
build_zmenunx() {
    d="$PKGDIR/zmenunx"
    name="gmenunx"
    repo="https://github.com/sugarkrap/zmenunx"
    desc="GMenuNX - application/game launcher"

    if [ -z "$MAKEIPK" ] || [ ! -x "$d/build-package.sh" ]; then
        echo "==> zmenunx: skipping (no ../piko toolchain, or no build-package.sh)"
        emit_entry "$name" "$repo" "$desc"
        return 0
    fi

    echo "==> zmenunx: building"
    if ( cd "$d" && ./build-package.sh --out "$OUTDIR" ); then
        ipk="$(newest_ipk 'gmenunx_*_piko.ipk' "$OUTDIR")"
        if [ -n "$ipk" ]; then
            emit_entry "$name" "$repo" "$desc" "$ipk"
        else
            echo "==> WARNING: zmenunx build reported success but no .ipk found in $OUTDIR" >&2
            emit_entry "$name" "$repo" "$desc"
        fi
    else
        echo "==> WARNING: zmenunx build failed -- listing without an ipk: URL" >&2
        emit_entry "$name" "$repo" "$desc"
    fi
}

# ---------------------------------------------------------------------
# otCraft -- tools/build-package.sh packages otcraft-smoke, the on-device
# diagnostic. The port has no playable game binary yet (see that script's
# own header), so that is what ships here, honestly labelled as such.
# ---------------------------------------------------------------------
build_otcraft() {
    d="$PKGDIR/otCraft"
    name="otcraft-smoke"
    repo="https://github.com/sugarkrap/otcraft"
    desc="otCraft software rasterizer smoke test (on-device diagnostic -- the full game has no playable binary yet)"

    if [ -z "$MAKEIPK" ] || [ ! -x "$d/tools/build-package.sh" ]; then
        echo "==> otCraft: skipping (no ../piko toolchain, or no tools/build-package.sh)"
        emit_entry "$name" "$repo" "$desc"
        return 0
    fi

    echo "==> otCraft: building smoke test + assets"
    if ( cd "$d" && make -f Makefile.piko assets smoke && tools/build-package.sh --out "$OUTDIR" ); then
        ipk="$(newest_ipk 'otcraft-smoke_*_piko.ipk' "$OUTDIR")"
        if [ -n "$ipk" ]; then
            emit_entry "$name" "$repo" "$desc" "$ipk"
        else
            echo "==> WARNING: otCraft build reported success but no .ipk found in $OUTDIR" >&2
            emit_entry "$name" "$repo" "$desc"
        fi
    else
        echo "==> WARNING: otCraft build failed -- listing without an ipk: URL" >&2
        emit_entry "$name" "$repo" "$desc"
    fi
}

# ---------------------------------------------------------------------
# otQuake -- no packaging script upstream yet, so the recipe lives here.
# otQuake's own Makefile already targets ../piko's toolchain directly
# (arm-unknown-linux-uclibcgnueabi, static EABI soft-float -- see its
# header), so `make strip` is enough to get quake-fb + quake-fb-launcher.
#
# The repo already ships its own card-layout wiring -- the `quake` wrapper
# script and quake.desktop both hardcode /mnt/card/.zaurus -- so staging
# just mirrors what those two files already assume.
#
# Ships the ENGINE ONLY: Quake's game data (id1/) is not redistributable
# and is not in the otQuake repo. The user supplies their own at
# /mnt/card/id1, same as every other Quake port. Must be installed to the
# card (`pkgadd N card`), never NAND -- the wrapper hardcodes the card path.
# ---------------------------------------------------------------------
build_otquake() {
    d="$PKGDIR/otQuake"
    name="otquake"
    repo="https://github.com/sugarkrap/otquake"
    desc="otQuake - framebuffer Quake engine (install to card; supply your own id1/ game data at /mnt/card/id1)"

    if [ -z "$MAKEIPK" ] || [ ! -x "$TOOLCHAIN_GCC" ]; then
        echo "==> otQuake: skipping (no ../piko toolchain built)"
        emit_entry "$name" "$repo" "$desc"
        return 0
    fi

    echo "==> otQuake: building quake-fb + quake-fb-launcher"
    stage="$(mktemp -d)"
    if ( cd "$d" && make strip ) \
        && mkdir -p "$stage/usr/bin" "$stage/usr/share/applications" \
        && cp -p "$d/quake-fb" "$d/quake-fb-launcher" "$d/quake" "$stage/usr/bin/" \
        && cp -p "$d/quake.desktop" "$stage/usr/share/applications/" \
        && "$MAKEIPK" --name "$name" --version "$(pkg_version "$d")" \
               --root "$stage" --arch piko --desc "$desc" --out "$OUTDIR"
    then
        ipk="$(newest_ipk 'otquake_*_piko.ipk' "$OUTDIR")"
        rm -rf "$stage"
        if [ -n "$ipk" ]; then
            emit_entry "$name" "$repo" "$desc" "$ipk"
        else
            echo "==> WARNING: otQuake build reported success but no .ipk found in $OUTDIR" >&2
            emit_entry "$name" "$repo" "$desc"
        fi
    else
        rm -rf "$stage"
        echo "==> WARNING: otQuake build failed -- listing without an ipk: URL" >&2
        emit_entry "$name" "$repo" "$desc"
    fi
}

build_zmenunx
build_otcraft
build_otquake

mv "$TMP_MANIFEST" "$MANIFEST"

built="$(grep -c '^    ipk:' "$MANIFEST" || true)"
echo
echo "==> wrote $MANIFEST ($built/3 packages have an ipk: URL)"
